stages:
  - lint

Lint:
  stage: lint
  tags:
    - bfs
  script:
    - cpplint --verbose=0 flight_code/include/flight/global_defs.h
    - cpplint --verbose=0 flight_code/include/flight/hardware_defs.h
    - cpplint --verbose=0 flight_code/include/flight/config.h
    - cpplint --verbose=0 flight_code/include/flight/msg.h
    - cpplint --verbose=0 flight_code/include/flight/sys.h
    - cpplint --verbose=0 flight_code/include/flight/sensors.h
    - cpplint --verbose=0 flight_code/include/flight/effectors.h
    - cpplint --verbose=0 flight_code/include/flight/nav.h
    - cpplint --verbose=0 flight_code/include/flight/control.h
    - cpplint --verbose=0 flight_code/include/flight/datalog.h
    - cpplint --verbose=0 flight_code/include/flight/telem.h
    - cpplint --verbose=0 flight_code/include/flight/analog.h
    - cpplint --verbose=0 flight_code/include/flight/battery.h
    - cpplint --verbose=0 flight_code/flight/flight.cc
    - cpplint --verbose=0 flight_code/flight/config.cc
    - cpplint --verbose=0 flight_code/flight/msg.cc
    - cpplint --verbose=0 flight_code/flight/sys.cc
    - cpplint --verbose=0 flight_code/flight/sensors.cc
    - cpplint --verbose=0 flight_code/flight/effectors.cc
    - cpplint --verbose=0 flight_code/flight/nav.cc
    - cpplint --verbose=0 flight_code/flight/control.cc
    - cpplint --verbose=0 flight_code/flight/datalog.cc
    - cpplint --verbose=0 flight_code/flight/telem.cc
    - cpplint --verbose=0 flight_code/flight/analog.cc
    - cpplint --verbose=0 flight_code/flight/battery.cc