stages:
  - lint

Lint:
  stage: lint
  tags:
    - bfs
  script: 
    - cpplint --verbose=0 include/flight/global_defs.h
    - cpplint --verbose=0 include/flight/hardware_defs.h
    - cpplint --verbose=0 include/flight/config.h
    - cpplint --verbose=0 include/flight/msg.h
    - cpplint --verbose=0 include/flight/sys.h
    - cpplint --verbose=0 include/flight/sensors.h
    - cpplint --verbose=0 include/flight/effectors.h
    - cpplint --verbose=0 include/flight/nav.h
    - cpplint --verbose=0 include/flight/control.h
    - cpplint --verbose=0 include/flight/datalog.h
    - cpplint --verbose=0 include/flight/telem.h
    - cpplint --verbose=0 flight/flight.cc
    - cpplint --verbose=0 flight/hardware_defs.cc
    - cpplint --verbose=0 flight/config.cc
    - cpplint --verbose=0 flight/msg.cc
    - cpplint --verbose=0 flight/sys.cc
    - cpplint --verbose=0 flight/sensors.cc
    - cpplint --verbose=0 flight/effectors.cc
    - cpplint --verbose=0 flight/nav.cc
    - cpplint --verbose=0 flight/control.cc
    - cpplint --verbose=0 flight/datalog.cc
    - cpplint --verbose=0 flight/telem.cc